- min
- max 
- len 
- sum 
- mean
- median
- mode
- variance
- covariance
- percentile
- quatile

In [3]:
import numpy as np 
l = list(range(1,20))
a = np.array(range(20,30))
arr1 = np.array(l) 
arr1,a

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))

In [6]:
a.tolist()

numpy.ndarray

In [10]:
Min = np.min(arr1)
Max = np.max(arr1)
Sum = np.sum(arr1) 
Min,Max,Sum

(np.int64(1), np.int64(19), np.int64(190))

In [11]:
np.count_nonzero(a)

10

In [15]:
mean = np.mean(arr1)
median=np.median(arr1)
mean,median

(np.float64(10.0), np.float64(10.0))

In [19]:
np.quantile(arr1,0.5)

np.float64(10.0)

In [20]:
np.var(arr1)

np.float64(30.0)

In [22]:
arr1_mean = np.mean(arr1) 
print(arr1_mean)
arr1- arr1_mean

10.0


array([-9., -8., -7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9.])

In [25]:
arr1 #1-20
arr1_mean = np.mean(arr1) 
arr2 = arr1-arr1_mean
arr3=np.square(arr2)
var = np.sum(arr3)/len(arr1)
var

np.float64(30.0)

In [26]:
np.sum(np.square (arr1-np.mean(arr1)))

np.float64(570.0)

In [27]:
arr1 
arr1_mean= np.mean(arr1) 
arr2=arr1-arr1_mean
arr3=np.square(arr2)
var= np.sum(arr3)/len(arr1)
np.sqrt(var)

np.float64(5.477225575051661)

In [32]:
l1 = [10,20]
l2 = [3,5]
arr1= np.array(l1)
arr2= np.array(l2)
np.sqrt(np.sum(np.square(arr1-arr2)))


np.float64(16.55294535724685)

In [33]:
#Covariance 
l1 = list(range(1,11))
l2 = list(range(21,31))
arr1 = np.array(l1)
arr2 = np.array(l2)
arr1_mean= np.mean(arr1)
arr2_mean= np.mean(arr2)
arr11 = arr1-arr1_mean
arr22 = arr2-arr2_mean
np.sum(arr11*arr22)/len(arr1)

np.float64(8.25)

In [34]:
arr1
arr2
arr1_mean
arr2_mean
arr11=arr1-arr1_mean
arr22=arr2-arr2_mean
np.sum(arr1*arr22)/len(arr1)

np.float64(8.25)

In [35]:
#linear algebra 
from numpy.linalg import eig,norm 
import numpy as np

In [36]:
l1=[10,20]   # (x1,y1)
l2=[3,5]     # (x2,y2)
arr1=np.array(l1)
arr2=np.array(l2)

In [37]:
norm(arr1),norm(arr2)

(np.float64(22.360679774997898), np.float64(5.830951894845301))

In [38]:
#cosine similarity 
A= [10,20]
B= [20,40]
arr1=np.array(A)
arr2=np.array(B)
arr1,arr2

(array([10, 20]), array([20, 40]))

In [39]:
import numpy as np

# Two vectors
A = np.array([1, 2, 3])
B = np.array([2, 4, 6])


# 1,2,3   numbers
# [1,2,3] list of numbers      :sclar
# array([1,2,3])  array of number: vector

In [40]:
Nr= np.dot(A,B)
Nr

np.int64(28)

In [41]:
Dr=norm(A)*norm(B)

In [42]:
Nr/Dr

np.float64(1.0)