In [ ]:
[10,20,30,40] #scaler
array ([10,20,30,40]) #vector machine learning
tensor([10,20,30,40]) #tensor (google) deep learning

In [5]:
import numpy as np


In [6]:
np.__version__

'2.2.6'

In [7]:
l1 = [10,20,30,40]
arr1 = np.array(l1)
arr1

array([10, 20, 30, 40])

In [10]:
l2 = [1,2,3,4]
arr2 = np.array(l2)
arr2

array([1, 2, 3, 4])

In [11]:
l1*l2

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
arr1*arr2

array([ 10,  40,  90, 160])

In [15]:
ans = []
for i,j in zip(l1,l2):
    ans.append(i*j)
ans

[10, 40, 90, 160]

In [16]:
arr1-arr2

array([ 9, 18, 27, 36])

In [20]:
import time 
start = time.time()
l1 = range (1,1000000)
l2 = range (1,1000000)
ans =[i*j for i,j in zip(l1,l2)]
end = time.time()
print(f'The total time taken :{end-start}')

The total time taken :0.15166401863098145


In [21]:
list (range (1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])